apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: postgres-demo
  labels:
    app.kubernetes.io/part-of: postgres-gitops-demo
spec:
  # Open source PostgreSQL operand, maintained by the CloudNativePG project.
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6

  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  bootstrap:
    initdb:
      database: app
      owner: app
